# Generated by Django 5.2.6 on 2025-12-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookMBTI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=4, unique=True, verbose_name="MBTI 코드"
                    ),
                ),
                ("info", models.TextField(verbose_name="MBTI 설명 / AI 프롬프트용")),
            ],
            options={
                "verbose_name": "도서 MBTI",
                "verbose_name_plural": "도서 MBTI 목록",
                "db_table": "book_mbti",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="book_mbti",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="BookMBTI 테이블의 id 값",
                null=True,
                verbose_name="책 MBTI ID",
            ),
        ),
    ]
