# Generated by Django 5.2.6 on 2025-12-23 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_bookmbti_alter_user_book_mbti"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="book_mbti",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.bookmbti",
                verbose_name="책 MBTI",
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
