# Generated by Django 5.2.6 on 2025-12-24 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='판매글 제목')),
                ('content', models.TextField(verbose_name='판매글 내용')),
                ('sale_type', models.CharField(choices=[('sale', '판매'), ('free', '무료나눔')], default='sale', max_length=10, verbose_name='판매 유형')),
                ('price', models.IntegerField(default=0, verbose_name='판매가격')),
                ('region', models.CharField(choices=[('all', '전국'), ('seoul', '서울특별시'), ('busan', '부산광역시'), ('daegu', '대구광역시'), ('incheon', '인천광역시'), ('gwangju', '광주광역시'), ('daejeon', '대전광역시'), ('ulsan', '울산광역시'), ('sejong', '세종특별자치시'), ('gyeonggi', '경기도'), ('gangwon', '강원특별자치도'), ('chungbuk', '충청북도'), ('chungnam', '충청남도'), ('jeonbuk', '전라북도'), ('jeonnam', '전라남도'), ('gyeongbuk', '경상북도'), ('gyeongnam', '경상남도'), ('jeju', '제주특별자치도')], max_length=20, verbose_name='거래 지역')),
                ('status', models.CharField(choices=[('available', '판매중'), ('reserved', '예약중'), ('sold', '판매완료')], default='available', max_length=20, verbose_name='거래 상태')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trade_images/', verbose_name='상품 이미지')),
                ('kakao_chat_url', models.URLField(blank=True, max_length=100, null=True, verbose_name='카카오톡 오픈채팅 URL')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='books.book', verbose_name='도서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
            ],
            options={
                'verbose_name': '중고거래',
                'verbose_name_plural': '중고거래',
                'db_table': 'trade',
                'indexes': [models.Index(fields=['user'], name='idx_trade_user'), models.Index(fields=['book'], name='idx_trade_book'), models.Index(fields=['status'], name='idx_trade_status'), models.Index(fields=['-created_at'], name='idx_trade_created'), models.Index(fields=['region'], name='idx_trade_region')],
            },
        ),
    ]
