# Generated by Django 5.2.6 on 2025-12-24 12:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='카테고리명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN-13')),
                ('title', models.CharField(max_length=200, verbose_name='도서명')),
                ('cover', models.URLField(blank=True, max_length=500, null=True, verbose_name='표지 이미지 URL')),
                ('price_standard', models.IntegerField(default=0, verbose_name='정가')),
                ('price_sales', models.IntegerField(default=0, verbose_name='판매가')),
                ('item_id', models.IntegerField(blank=True, help_text='알라딘 API 상품 ID', null=True, verbose_name='알라딘 상품 ID')),
                ('mall_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='판매처')),
                ('publisher', models.CharField(max_length=100, verbose_name='출판사')),
                ('author', models.CharField(max_length=200, verbose_name='저자')),
                ('description', models.TextField(blank=True, null=True, verbose_name='도서 소개')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='출판일')),
                ('adult', models.BooleanField(default=False, verbose_name='성인 도서 여부')),
                ('customer_review_rank', models.IntegerField(blank=True, help_text='알라딘 고객 리뷰 랭킹 (0~10)', null=True, verbose_name='알라딘 고객 리뷰 랭킹')),
                ('best_rank', models.IntegerField(blank=True, help_text='알라딘 베스트셀러 순위', null=True, verbose_name='알라딘 베스트셀러 순위')),
                ('sales_point', models.IntegerField(default=0, help_text='알라딘 API salesPoint 값 (누적 판매/인기 지표)', verbose_name='알라딘 판매 지수')),
                ('rating_count', models.IntegerField(default=0, help_text='BookRating 테이블에서 자동 계산', verbose_name='평점 개수')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='BookRating 테이블에서 자동 계산 (0.00~5.00)', max_digits=3, verbose_name='평균 평점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '도서',
                'verbose_name_plural': '도서',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='books.book', verbose_name='도서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '북마크',
                'db_table': 'bookmark',
                'indexes': [models.Index(fields=['book'], name='idx_bookmark_book')],
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book_bookmark')],
            },
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, help_text='0.0 ~ 5.0', max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='평점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='books.book', verbose_name='도서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '도서 평점',
                'verbose_name_plural': '도서 평점',
                'db_table': 'book_rating',
                'indexes': [models.Index(fields=['book'], name='idx_book_rating_book'), models.Index(fields=['-score'], name='idx_book_rating_score')],
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book_rating')],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category'], name='idx_book_category'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='idx_book_isbn'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-average_rating'], name='idx_book_rating'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created_at'], name='idx_book_created'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-best_rank'], name='idx_book_best_rank'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-customer_review_rank'], name='idx_book_review_rank'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-sales_point'], name='idx_book_sales_point'),
        ),
    ]
