# Generated by Django 6.0 on 2025-12-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category_name',
        ),
        migrations.AddField(
            model_name='book',
            name='best_rank',
            field=models.IntegerField(blank=True, help_text='알라딘 베스트셀러 순위', null=True, verbose_name='알라딘 베스트셀러 순위'),
        ),
        migrations.AddField(
            model_name='book',
            name='customer_review_rank',
            field=models.IntegerField(blank=True, help_text='알라딘 고객 리뷰 랭킹 (0~10)', null=True, verbose_name='알라딘 고객 리뷰 랭킹'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-best_rank'], name='idx_book_best_rank'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-customer_review_rank'], name='idx_book_review_rank'),
        ),
    ]
