# Generated by Django 5.2.4 on 2025-12-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_category_name_book_best_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sales_point',
            field=models.IntegerField(blank=True, help_text='알라딘 판매지수 (높을수록 많이 팔림)', null=True, verbose_name='알라딘 판매지수'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-sales_point'], name='idx_book_sales_point'),
        ),
    ]
