# Generated by Django 5.2.6 on 2025-12-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_remove_book_category_name_book_best_rank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="sales_point",
            field=models.IntegerField(
                default=0,
                help_text="알라딘 API salesPoint 값 (누적 판매/인기 지표)",
                verbose_name="알라딘 판매 지수",
            ),
        ),
    ]
