# Generated by Django 5.2.6 on 2025-12-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_sales_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="sales_point",
            field=models.IntegerField(
                blank=True,
                help_text="알라딘 API salesPoint 값 (누적 판매/인기 지표)",
                null=True,
                verbose_name="알라딘 판매 지수",
            ),
        ),
    ]
