# Generated by Django 5.2.6 on 2025-12-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_sales_point"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="sales_point",
        ),
    ]
